config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  #GET /about
  get "/about-us", to: "about#index", as: :about
  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        flash[:notice]= "Logged in successfully"
        flash[:alert]= "Invalid email or password"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render partial: "shared/navbar"  %>
    <div class="container">
        <%= render partial: "shared/flash" %>
        <%= yield %>
    </div>
</body>

</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
Welcome to Scheduled Tweets!
</div>

app/views/shared/_flash.html.erb
<div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
</div>
<div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <%= link_to "Home", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "About", about_path, class: "nav-link" %>
                </li>
            </ul>
        </div>
    </div>
</nav>